name: Default (push)

on:
  pull_request:
    branches:
      - master
      - develop
      - feature/*
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - v*

defaults:
  run:
    shell: bash

env:
  REPO: docksal/docksal
  DOCKSAL_SSH_AGENT_USE_HOST: 0
  IMAGE_VHOST_PROXY: 'docksal/vhost-proxy:fix-container-id'
  CI: ''

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        suite:
          #- quicktest # Uncomment to run
          - project
          - config
          - db
          - system
          - commands
          #- acquia
          #- pantheon
          #- platform
          #- drush
          #- wp

    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Checkout custom vhost-proxy image source
        uses: actions/checkout@v2
        with:
          repository: docksal/service-vhost-proxy
          ref: 'bug/github-actions-no-container-id'
          path: service-vhost-proxy
      - 
        name: Build substitute docksal/vhost-proxy image
        env:
          BUILD_TAG: 'fix-container-id'
        run: |
          cd ${GITHUB_WORKSPACE}/service-vhost-proxy
          make
      -
        name: "Install SSH Key Key"
        run: |
          mkdir $HOME/.ssh || true
          echo "${SSH_KEY}" | base64 --decode > $HOME/.ssh/project_key
          chmod 400 $HOME/.ssh/project_key
        env:
          SSH_KEY: ${{ env.SSH_KEY }}
      -
        name: "Install modified version of BATS"
        run: |
          git clone https://github.com/docksal/bats.git tests/scripts/bats
          sudo tests/scripts/bats/install.sh /usr/local
          bats -v
      -
        name: "Install version of Fin within current branch"
        run: sudo cp ./bin/fin /usr/local/bin/fin
      -
        name: "Current Version of Fin"
        run: fin version
      -
        name: "Calculate correct branch to use"
        id: use_branch
        run: |
          USE_BRANCH="$(echo ${GITHUB_REF#refs/heads/})"
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" && "${GITHUB_REPOSITORY}" == "${REPO}" ]]; then USE_BRANCH="${PR_BRANCH}"; fi
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" && "${GITHUB_REPOSITORY}" != "${REPO}" ]]; then USE_BRANCH='develop'; fi
          echo "##[set-output name=branch;]$(echo ${USE_BRANCH})"
        env:
          PR_BRANCH: ${{ github.base_ref }}
      -
        name: "Run Fin Update to Install Tools"
        run: fin update
        env:
          DOCKSAL_VERSION: ${{ steps.use_branch.outputs.branch }}
      -
        name: "Get information about system"
        run: fin sysinfo
      -
        name: "Execute tests"
        run: tests/scripts/${SUITE}.sh
        env:
          SUITE: ${{ matrix.suite }}
          SERVICE_VHOST_PROXY_VERSION: 'fix-container-id'
      # Commenting out at the moment until repos are converted over to GithuB Actions
      #-
      #   if: ${{ matrix.suite }} == "project"
      #   name: "Execute Boilerplate Tests"
      #   run: tests/scripts/boilerplates.sh

